feat: blog redesign
masterborn/ockam-website-fork-1 pull request #12
Opened 2022-07-07 14:34 UTC by alojzy231

2022-07-08 11:06 UTC, alojzy231 commented on src/components/ImageWithPlaceholder.tsx
> +  placeholderImg: StaticImageData;
unnecessary removed string

2022-07-08 12:38 UTC, alojzy231 commented on src/contextProviders/SearchValueProvider.tsx
> +import { createContext, FunctionComponent, ReactNode, useState, useMemo } from 'react';
search after clicking on icon or enter

2022-07-08 12:38 UTC, alojzy231 commented on src/views/blog/FilteredPosts.tsx
> +  const [searchPosts, setSearchPosts] = useState<BlogPost[]>([]);
useMemo()

2022-07-08 12:38 UTC, alojzy231 commented on src/components/SearchInput.tsx
> +      <Input
variant="outline", style in theme/components

2022-07-08 12:38 UTC, alojzy231 commented on src/components/mdx/index.js
> +    <Heading as="h2" fontSize={{ base: 'xl', sm: '3xl' }} mb={{ base: 6, sm: 10 }} {...props} />
change to corresponding heading tag (h1 -> h1)

2022-07-08 12:38 UTC, alojzy231 commented on src/consts/placeholderImages.ts
> +import PlaceholderOneImage from '@assets/images/placeholders/placeholder1.png';
direct import

2022-07-08 12:38 UTC, alojzy231 commented on src/views/blog/components/GenericPost.tsx
> +import PLACEHOLDERS from '@consts/placeholderImages';
direct import

2022-07-08 12:38 UTC, alojzy231 commented on src/layouts/MainLayout/MainLayoutHeader.tsx
> +  const { isBelowSmallLaptop } = useLayoutMobileNav();
useContext()

2022-07-12 08:26 UTC, lukasztucholski requested changes
Let's rename placeholders for blog post to sth like "placeholder-blog-post-silver" etc  

2022-07-12 08:26 UTC, lukasztucholski commented on src/pages/blog/[slug].tsx
> +      <PostTopSection post={frontMatter as BlogPostData} />
RC: BlogPostHeader

2022-07-12 08:26 UTC, lukasztucholski commented on src/pages/blog/[slug].tsx
> +      <PostContent>
RC: BlogPostContent

2022-07-12 08:26 UTC, lukasztucholski commented on src/pages/blog/index.tsx
> +    <TopSection />
RC: BlogPageHeader

2022-07-12 08:26 UTC, lukasztucholski commented on src/pages/blog/index.tsx
> +    <PostsSection posts={posts} />
RC: BlogPosts

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/FeaturedPosts.tsx
> +    <GenericPost post={topFeaturedPost} display={{ base: 'block', '1.5xl': 'none' }} />
RC: BlogPostCard

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/FeaturedPosts.tsx
> +    <TopFeaturedPost post={topFeaturedPost} display={{ base: 'none', '1.5xl': 'block' }} />
RC: FeaturedBlogPost

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/FeaturedPosts.tsx
> +  topFeaturedPost,
RC: highlightFeaturedPost or smth like that

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/FeaturedPosts.tsx
> +  orderedFeaturedPost,
RC: restFeaturedPosts

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/FeaturedPosts.tsx
> +const FeaturedPosts: FunctionComponent<FeaturedPostsProps> = ({
RC: FeaturedBlogPosts

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/PostsSection.tsx
> +  const deferredSearchValue = useDeferredValue(searchValue);
RC: unnecessary deferred value

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/PostsSection.tsx
> +const PostsSection: FunctionComponent<PostsSectionProps> = ({ posts }) => {
RC: BlogPosts

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/TopSection.tsx
> +  const deferredSearchValue = useDeferredValue(searchValue);
RC: unnecessary deferred value

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/components/CategoryBadge.tsx
> +        borderRadius="0 0 4px 0"
TIP: Chakra has props "borderRightBottomRadius" or smth like that.

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/SlugPost/PostContent.tsx
> +    fontFamily="'Source Serif Pro', serif"
Moved it to theme

2022-07-12 08:26 UTC, lukasztucholski commented on src/views/blog/PostsSection.tsx
> +  const searchPosts = useMemo(
Moved it to Search context

2022-07-12 08:26 UTC, lukasztucholski commented on src/layouts/BlogLayout/BlogLayoutSidebar/BlogLayoutSidebarSeeAllArticles.tsx
> +  const handleRemoveSearchQuery = (): void => {
RC: move it to search context

2022-07-12 08:26 UTC, lukasztucholski commented on src/layouts/BlogLayout/BlogLayoutSidebar/BlogLayoutSidebarSeeAllArticles.tsx
> +      <Link href="/blog">
RC: passHref, move href to const with paths

2022-07-12 08:26 UTC, lukasztucholski commented on src/layouts/BlogLayout/BlogLayoutSocials.tsx
> +      FOLLOW OR VISIT US ON
RC: Let's write in with lowercase and pass props textTransform = uppercase

2022-07-12 08:26 UTC, lukasztucholski commented on src/layouts/BlogLayout/BlogLayoutSocials.tsx
> +      <Link href="https://www.linkedin.com/company/ockam.io/" isExternal>
RC: move link to const in global consts folder

2022-07-12 08:26 UTC, lukasztucholski commented on src/layouts/BlogLayout/BlogLayoutSidebar/BlogLayoutSidebarPostLink.tsx
> +    <Link as={`/blog/${post.filePath.replace(/\.mdx?$/, '')}`} href="/blog/[slug]">
RC: passHref & moved 'blog' to paths in consts

2022-07-12 08:26 UTC, lukasztucholski commented on src/layouts/BlogLayout/BlogLayoutSidebar/BlogLayoutSidebarSeeAllArticles.tsx
> +            '&:active svg': {
_active: {
svg: {
//
}
}

2022-07-12 08:26 UTC, lukasztucholski commented on src/layouts/BlogLayout/BlogLayoutSocials.tsx
> +    <Heading as="h5" fontSize="sm" fontWeight={500}>
Q: fontWieght="regular" ?

2022-07-12 08:26 UTC, lukasztucholski commented on src/layouts/BlogLayout/BlogLayoutSocials.tsx
> +      <Link href="https://www.linkedin.com/company/ockam.io/" isExternal>
RC: render links in loop

2022-07-12 10:58 UTC, lukasztucholski approved these changes
Great work! 🥳

2022-07-12 11:05 UTC, merged